# Stage 1: Build with Maven
FROM maven:3.8.4-openjdk-17 AS builder

WORKDIR /app

COPY ./src ./src
COPY ./pom.xml .

RUN mvn clean package

# Stage 2: Create the final image
FROM openjdk:17-jdk-alpine

WORKDIR /app

VOLUME /tmp

ARG JAR_FILE=target/*.jar

# Copy the JAR file from the builder stage
COPY --from=builder /app/${JAR_FILE} app.jar

ENTRYPOINT ["java", "-jar", "app.jar"]
